version: "3.1"
services:

  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - 81:3000
    volumes:
      - ./web/src:/app/src

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 3001:27017
    volumes:
      - mongodata:/data/db
    command: mongod --quiet --logpath /dev/null


volumes:
  mongodata:
